[workspace]
members = [
    "contracts/*",
    "packages/*",
]
resolver = "2"

[workspace.package]
version       = "0.1.0"
edition       = "2021"
license       = "Apache-2.0"
repository    = "https://github.com/srdtrk/cw-ibc-lite"
rust-version  = "1.77"
keywords      = ["cosmos", "cosmwasm", "ibc"]
authors       = ["srdtrk <srdtrk@hotmail.com>"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
panic = 'abort'
rpath = false
# Please do not disable these. Doing so will cause overflow checks in
# all workspace members to stop working. Overflows should be errors.
overflow-checks = true

[workspace.dependencies]
cosmwasm-schema = "1.5.5"
cosmwasm-std = { version = "1.5.5", features = [
  # Enable this if you only deploy to chains that have CosmWasm 1.4 or higher
  "cosmwasm_1_4",
  "stargate",
] }
cw-storage-plus = "1.2.0"
cw2 = "1.1.2"
cw20 = "1.1.2"
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.58" }
cw-ownable = "0.5.1"
ibc-core-host = { version = "0.53.0", default-features = false, features = ["schema"] }
ibc-client-cw = { version = "0.53.0", default-features = false }
ibc-client-tendermint = { version = "0.53.0", default-features = false, features = ["schema"] }
cw-ibc-lite-shared = { version = "0.1.0", path = "./packages/shared/" }
cw-ibc-lite-derive = { version = "0.1.0", path = "./packages/derive/" }
cw-ibc-lite-ics02-client = { version = "0.1.0", path = "./contracts/ics02-client/", default-features = false }
cw-ibc-lite-ics26-router = { version = "0.1.0", path = "./contracts/ics26-router/", default-features = false }
sha2 = "0.10.8"
ibc-proto = { version = "0.44.0", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = [ "from", "into", "display", "try_into" ] }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["derive"] }
