[package]
name = "cw-ibc-lite-ics07-tendermint"
description = "IBC Lite Router for CosmWasm"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
# exclude export feature to disable all instantiate/execute/query exports
default = ["export"]
export = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
ibc-client-cw = { workspace = true }
ibc-client-tendermint = { workspace = true }
cw-ibc-lite-shared = { workspace = true }
